@startuml HyperTask_ERD
entity users{
    * id AI PK
    * name String
    * email String
    * password String
}
entity projects{
    * id AI PK
    * title String
    description String
    * status String
    * user_id Integer FK users.id
}

entity task_groups{
    * id AI PK
    * title String
    * groupable_id Integer FK (users.id,projects.id)
    * groupable_type String (User,Project)
}

entity tasks{
    * id AI PK
    * body String
    * status String
    * taskable_id Integer FK (users.id,projects.id,task_groups.id)
    * taskable_type String FK (User,Project,TaskGroup)
}

tasks }o-- users
tasks }o-- projects
projects }o-- users
task_groups }o-- projects
task_groups }o-- users
tasks }o-- task_groups
@enduml